In [8]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
df = pd.read_csv('diabetes_data_train_710samples.csv')

In [3]:
df.head(2)

Row  preg_count  glucose_concentration  diastolic_bp  \
0    0           6                    148            72   
1    1           1                     85            66   

   triceps_skin_fold_thickness  two_hr_serum_insulin   bmi  diabetes_pedi  \
0                           35                     0  33.6          0.627   
1                           29                     0  26.6          0.351   

   age  diabetes_class  
0   50               1  
1   31               0

In [6]:
df.corrwith(df['diastolic_bp'])

Row                           -0.011381
preg_count                     0.142042
glucose_concentration          0.146026
diastolic_bp                   1.000000
triceps_skin_fold_thickness    0.211979
two_hr_serum_insulin           0.101921
bmi                            0.279390
diabetes_pedi                  0.040030
age                            0.237515
diabetes_class                 0.058391
dtype: float64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 710 entries, 0 to 709
Data columns (total 10 columns):
Row                            710 non-null int64
preg_count                     710 non-null int64
glucose_concentration          710 non-null int64
diastolic_bp                   710 non-null int64
triceps_skin_fold_thickness    710 non-null int64
two_hr_serum_insulin           710 non-null int64
bmi                            710 non-null float64
diabetes_pedi                  710 non-null float64
age                            710 non-null int64
diabetes_class                 710 non-null int64
dtypes: float64(2), int64(8)
memory usage: 55.5 KB


### Feature and target

In [8]:
df.columns

Index(['Row', 'preg_count', 'glucose_concentration', 'diastolic_bp',
       'triceps_skin_fold_thickness', 'two_hr_serum_insulin', 'bmi',
       'diabetes_pedi', 'age', 'diabetes_class'],
      dtype='object')

In [10]:
X = df[['preg_count', 'glucose_concentration', 'diastolic_bp',
       'triceps_skin_fold_thickness', 'two_hr_serum_insulin', 'bmi',
       'diabetes_pedi', 'age']]
y = df['diabetes_class']

In [63]:
df.corr()

Row  preg_count  glucose_concentration  \
Row                          1.000000   -0.049529              -0.003177   
preg_count                  -0.049529    1.000000               0.137212   
glucose_concentration       -0.003177    0.137212               1.000000   
diastolic_bp                -0.011381    0.142042               0.146026   
triceps_skin_fold_thickness  0.003161   -0.096404               0.055279   
two_hr_serum_insulin         0.005083   -0.069093               0.327807   
bmi                         -0.012753    0.020589               0.220797   
diabetes_pedi               -0.030718   -0.048586               0.139026   
age                         -0.007847    0.546881               0.277794   
diabetes_class              -0.063441    0.230506               0.458086   

                             diastolic_bp  triceps_skin_fold_thickness  \
Row                             -0.011381                     0.003161   
preg_count                       0.142042                    -0.096404   
glucose_concentration            0.146026                     0.055279   
diastolic_bp                     1.000000                     0.211979   
triceps_skin_fold_thickness      0.211979                     1.000000   
two_hr_serum_insulin             0.101921                     0.440467   
bmi                              0.279390                     0.385673   
diabetes_pedi                    0.040030                     0.181029   
age                              0.237515                    -0.116000   
diabetes_class                   0.058391                     0.084880   

                             two_hr_serum_insulin       bmi  diabetes_pedi  \
Row                                      0.005083 -0.012753      -0.030718   
preg_count                              -0.069093  0.020589      -0.048586   
glucose_concentration                    0.327807  0.220797       0.139026   
diastolic_bp                             0.101921  0.279390       0.040030   
triceps_skin_fold_thickness              0.440467  0.385673       0.181029   
two_hr_serum_insulin                     1.000000  0.200392       0.189800   
bmi                                      0.200392  1.000000       0.138409   
diabetes_pedi                            0.189800  0.138409       1.000000   
age                                     -0.026111  0.036475       0.036862   
diabetes_class                           0.137614  0.291296       0.172729   

                                  age  diabetes_class  
Row                         -0.007847       -0.063441  
preg_count                   0.546881        0.230506  
glucose_concentration        0.277794        0.458086  
diastolic_bp                 0.237515        0.058391  
triceps_skin_fold_thickness -0.116000        0.084880  
two_hr_serum_insulin        -0.026111        0.137614  
bmi                          0.036475        0.291296  
diabetes_pedi                0.036862        0.172729  
age                          1.000000        0.231088  
diabetes_class               0.231088        1.000000

### Split into test and train

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [12]:
from sklearn.linear_model import LogisticRegression
logr = LogisticRegression(solver='liblinear')
logr.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [13]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [15]:
from sklearn.naive_bayes import MultinomialNB

In [16]:
algos = [KNeighborsClassifier(), LogisticRegression(), MultinomialNB()]
for algo in algos:
    algo.fit(X_train,y_train)
    y_algo_pred=algo.predict(X_test)
    print("Acc: ", sum(y_algo_pred==y_test)/len(y_test))

Acc:  0.6619718309859155
Acc:  0.755868544600939
Acc:  0.6619718309859155


In [86]:
y_knn_pred = knn.predict(X_test)

In [87]:
sum(y_test == y_knn_pred)/len(y_test)

0.6619718309859155

In [66]:
y_pred = logr.predict(X_test)
y_pred[:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [71]:
logr.coef_, logr.intercept_

(array([[ 1.08255884e-01,  2.65746916e-02, -1.64993845e-02,
          2.17468908e-03, -6.66851663e-04,  4.51539755e-02,
          7.31051069e-01,  9.16850278e-03]]), array([-5.28904378]))

In [67]:
len(df), len(df[df['diabetes_class']==1]), len(df[df['diabetes_class']==0])

(710, 246, 464)

In [68]:
464/710

0.6535211267605634

In [75]:
df_prob = pd.DataFrame(logr.predict_proba(X_test), columns = ['NO', 'YES'])

In [79]:
sum(df_prob['NO'] > 0.7)

97

In [69]:
sum(y_pred == y_test)

161

In [60]:
len(y_test)

213

In [70]:
161/213

0.755868544600939

In [19]:
sum(y_pred == y_test)

161

In [20]:
len(y_pred)

213

- load diabetes data set

In [2]:
df = pd.read_csv('diabetes_data_train_710samples.csv')

In [3]:
df.head(3)

Row  preg_count  glucose_concentration  diastolic_bp  \
0    0           6                    148            72   
1    1           1                     85            66   
2    2           8                    183            64   

   triceps_skin_fold_thickness  two_hr_serum_insulin   bmi  diabetes_pedi  \
0                           35                     0  33.6          0.627   
1                           29                     0  26.6          0.351   
2                            0                     0  23.3          0.672   

   age  diabetes_class  
0   50               1  
1   31               0  
2   32               1

In [31]:
df.corr()

Row  preg_count  glucose_concentration  \
Row                          1.000000   -0.049529              -0.003177   
preg_count                  -0.049529    1.000000               0.137212   
glucose_concentration       -0.003177    0.137212               1.000000   
diastolic_bp                -0.011381    0.142042               0.146026   
triceps_skin_fold_thickness  0.003161   -0.096404               0.055279   
two_hr_serum_insulin         0.005083   -0.069093               0.327807   
bmi                         -0.012753    0.020589               0.220797   
diabetes_pedi               -0.030718   -0.048586               0.139026   
age                         -0.007847    0.546881               0.277794   
diabetes_class              -0.063441    0.230506               0.458086   

                             diastolic_bp  triceps_skin_fold_thickness  \
Row                             -0.011381                     0.003161   
preg_count                       0.142042                    -0.096404   
glucose_concentration            0.146026                     0.055279   
diastolic_bp                     1.000000                     0.211979   
triceps_skin_fold_thickness      0.211979                     1.000000   
two_hr_serum_insulin             0.101921                     0.440467   
bmi                              0.279390                     0.385673   
diabetes_pedi                    0.040030                     0.181029   
age                              0.237515                    -0.116000   
diabetes_class                   0.058391                     0.084880   

                             two_hr_serum_insulin       bmi  diabetes_pedi  \
Row                                      0.005083 -0.012753      -0.030718   
preg_count                              -0.069093  0.020589      -0.048586   
glucose_concentration                    0.327807  0.220797       0.139026   
diastolic_bp                             0.101921  0.279390       0.040030   
triceps_skin_fold_thickness              0.440467  0.385673       0.181029   
two_hr_serum_insulin                     1.000000  0.200392       0.189800   
bmi                                      0.200392  1.000000       0.138409   
diabetes_pedi                            0.189800  0.138409       1.000000   
age                                     -0.026111  0.036475       0.036862   
diabetes_class                           0.137614  0.291296       0.172729   

                                  age  diabetes_class  
Row                         -0.007847       -0.063441  
preg_count                   0.546881        0.230506  
glucose_concentration        0.277794        0.458086  
diastolic_bp                 0.237515        0.058391  
triceps_skin_fold_thickness -0.116000        0.084880  
two_hr_serum_insulin        -0.026111        0.137614  
bmi                          0.036475        0.291296  
diabetes_pedi                0.036862        0.172729  
age                          1.000000        0.231088  
diabetes_class               0.231088        1.000000

In [4]:
df.columns

Index(['Row', 'preg_count', 'glucose_concentration', 'diastolic_bp',
       'triceps_skin_fold_thickness', 'two_hr_serum_insulin', 'bmi',
       'diabetes_pedi', 'age', 'diabetes_class'],
      dtype='object')

- select features and target

In [4]:
X = df[['preg_count', 'glucose_concentration', 'diastolic_bp',
       'triceps_skin_fold_thickness', 'two_hr_serum_insulin', 'bmi',
       'diabetes_pedi', 'age']]
y = df['diabetes_class']

- split the data set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

- import LogisticRegression from sklearn.linear_model
- create an object
- fit

In [18]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [19]:
import pickle
fh = open('diab_pred_dec2.pkl', 'wb')
pickle.dump(lr,fh)
fh.close()

In [8]:
lr.coef_, lr.intercept_

(array([[ 1.08255884e-01,  2.65746916e-02, -1.64993845e-02,
          2.17468908e-03, -6.66851663e-04,  4.51539755e-02,
          7.31051069e-01,  9.16850278e-03]]), array([-5.28904378]))

In [10]:
len(X_test), len(X_train), len(y_test), len(y_train)

(213, 497, 213, 497)

- predict the value

In [14]:
y_pred = lr.predict(X_test)

In [17]:
sum(y_pred == y_test), len(y_test)

(161, 213)

In [18]:
161/213

0.755868544600939

In [20]:
sum(df['diabetes_class'] == 0), len(df)

(464, 710)

In [21]:
464/710

0.6535211267605634

In [22]:
lr.score(X_test,y_test)

0.755868544600939

In [9]:
import pickle
fh = open('diab_pred.pkl', 'wb')
pickle.dump(lr,fh)
fh.close()

- another metric confusion matrix 
- import confustion_matrix from sklearn.metrics
- tn, fp, fn, tp

In [23]:
from sklearn.metrics import confusion_matrix
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

In [26]:
confusion_matrix(y_test, y_pred).ravel()

array([119,  18,  34,  42], dtype=int64)

In [27]:
tn, fp, fn, tp

(119, 18, 34, 42)

In [28]:
lr.predict([[3,116,94,0,0,25.6,0.201,30]])

array([0], dtype=int64)

In [29]:
lr.predict_proba([[3,116,94,0,0,25.6,0.201,30]])

array([[0.86466816, 0.13533184]])

- change threshold by running predict_proba instead of predict

In [73]:
y_prob_pred  = lr.predict_proba(X_test)

In [74]:
print(y_prob_pred[:5])
print(y_pred[:5])


[[0.94426142 0.05573858]
 [0.7538062  0.2461938 ]
 [0.65688905 0.34311095]
 [0.90724859 0.09275141]
 [0.84529674 0.15470326]]
[0 0 0 0 0]


In [76]:
y_my_pred = [ 0 if p < 0.2 else 1 for n,p in y_prob_pred]
tn, fp, fn, tp = confusion_matrix(y_test, y_my_pred).ravel()
tn,fp,fn,tp

(59, 78, 6, 70)