In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

- load diabetes data set

In [2]:
df = pd.read_csv('diabetes_data_train_710samples.csv')

In [3]:
df.head(3)

Row  preg_count  glucose_concentration  diastolic_bp  \
0    0           6                    148            72   
1    1           1                     85            66   
2    2           8                    183            64   

   triceps_skin_fold_thickness  two_hr_serum_insulin   bmi  diabetes_pedi  \
0                           35                     0  33.6          0.627   
1                           29                     0  26.6          0.351   
2                            0                     0  23.3          0.672   

   age  diabetes_class  
0   50               1  
1   31               0  
2   32               1

In [4]:
df.columns

Index(['Row', 'preg_count', 'glucose_concentration', 'diastolic_bp',
       'triceps_skin_fold_thickness', 'two_hr_serum_insulin', 'bmi',
       'diabetes_pedi', 'age', 'diabetes_class'],
      dtype='object')

- select features and target

In [5]:
X = df[['preg_count', 'glucose_concentration', 'diastolic_bp',
       'triceps_skin_fold_thickness', 'two_hr_serum_insulin', 'bmi',
       'diabetes_pedi', 'age']]
y = df['diabetes_class']

- split the data set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [15]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()

In [16]:
dtc.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [17]:
y_pred = dtc.predict(X_test)

In [18]:
from sklearn.metrics import confusion_matrix

In [19]:
dtc.score(X_test, y_test)

0.7276995305164319

In [20]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
tf = RandomForestClassifier()

In [22]:
tf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [23]:
tf.score(X_test, y_test)

0.7089201877934272

- import LogisticRegression from sklearn.linear_model
- create an object
- fit

In [14]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [25]:
import pickle

In [26]:
fh = open('diab_pred.pkl', 'wb')
pickle.dump(lr,fh)
fh.close()

- predict the value

In [11]:
y_pred = lr.predict(X_test)

In [12]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1], dtype=int64)

- metrics for LR  - lr.score(X_test, y_test)

In [26]:
len(df[df['diabetes_class'] == 0])

464

In [27]:
len(df)

710

In [28]:
464/710

0.6535211267605634

In [18]:
check = pd.DataFrame({'actual': y_test, 'predicted': y_pred})
len(check[check['actual']==check['predicted']]), len(check)

(161, 213)

In [19]:
161/213

0.755868544600939

In [13]:
lr.score(X_test, y_test)

0.755868544600939

- another metric confusion matrix 
- import confustion_matrix from sklearn.metrics
- tn, fp, fn, tp

In [71]:
from sklearn.metrics import confusion_matrix
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

In [72]:
tn, fp, fn, tp

(119, 18, 34, 42)

- change threshold by running predict_proba instead of predict

In [73]:
y_prob_pred  = lr.predict_proba(X_test)

In [74]:
print(y_prob_pred[:5])
print(y_pred[:5])


[[0.94426142 0.05573858]
 [0.7538062  0.2461938 ]
 [0.65688905 0.34311095]
 [0.90724859 0.09275141]
 [0.84529674 0.15470326]]
[0 0 0 0 0]


In [76]:
y_my_pred = [ 0 if p < 0.2 else 1 for n,p in y_prob_pred]
tn, fp, fn, tp = confusion_matrix(y_test, y_my_pred).ravel()
tn,fp,fn,tp

(59, 78, 6, 70)