In [2]:
import numpy as np

### From Python list

In [3]:
my_list = [4,6,3,6,9]
my_list

[4, 6, 3, 6, 9]

In [4]:
np.array(my_list)

array([4, 6, 3, 6, 9])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [8]:
np.arange(30,step=2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

### zeros and ones

Generate arrays of zeros or ones

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

### linspace
Return evenly spaced numbers over a specified interval.

In [13]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

## eye

Creates an identity matrix

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [15]:
np.random.rand(3)

array([0.15996449, 0.28781582, 0.8869832 ])

In [16]:
np.random.rand(5,5)

array([[9.73730965e-01, 9.69355270e-02, 5.19238722e-01, 2.36031987e-01,
        9.96839291e-01],
       [8.99700160e-01, 2.72824548e-01, 5.73478207e-01, 5.69729477e-01,
        3.09600550e-01],
       [1.68934885e-01, 5.49048845e-01, 2.47742061e-01, 6.91490560e-01,
        6.52749558e-01],
       [2.08768854e-01, 2.86574943e-01, 2.89432507e-04, 5.58180121e-01,
        4.79268131e-01],
       [5.22297536e-01, 8.62652295e-01, 5.29607622e-01, 8.89803086e-01,
        2.68202154e-01]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [22]:
np.random.randn(2)

array([ 0.42620726, -0.39024736])

In [23]:
np.random.randn(5,5)

array([[ 1.21382642,  2.34697672, -0.8708024 ,  0.64534389, -1.62097598],
       [-0.630677  ,  2.2435754 ,  0.20023548, -0.45762126,  0.25663389],
       [-0.45977171, -0.15464403, -0.14477493, -0.67914867, -1.37803998],
       [-1.94845477, -1.04603939, -0.27959778,  1.07713029, -0.07594146],
       [ 0.00937235,  1.38655123,  1.31178501,  0.33864928,  3.06466437]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [24]:
np.random.randint(1,100)

18

In [25]:
np.random.randint(1,100,10)

array([95, 19, 19, 91, 32, 76, 20, 99,  5, 18])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [55]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

## Reshape
Returns an array containing the same data with a new shape.
.reshape(...) . But the number of items should remain the same

In [32]:
np.random.rand(1,200).reshape(10,20)

array([[0.94144501, 0.78447552, 0.34612753, 0.22692987, 0.40257054,
        0.53153569, 0.00470257, 0.659604  , 0.11451079, 0.78821566,
        0.87258485, 0.64057708, 0.15977792, 0.61307877, 0.01586517,
        0.84379269, 0.78104921, 0.22206928, 0.011888  , 0.43371191],
       [0.1683789 , 0.42160291, 0.38834345, 0.96836253, 0.26103521,
        0.24027113, 0.7254873 , 0.56578735, 0.54088168, 0.88061428,
        0.41699492, 0.09178144, 0.57420261, 0.56716857, 0.54306617,
        0.18255181, 0.77772968, 0.8825862 , 0.87672028, 0.58370821],
       [0.79007486, 0.45887435, 0.38256062, 0.37114852, 0.96572059,
        0.67585867, 0.98988281, 0.14086691, 0.48746489, 0.97036576,
        0.37850985, 0.64183327, 0.14337792, 0.51916619, 0.51755342,
        0.30918827, 0.37032655, 0.15107263, 0.06526144, 0.86109371],
       [0.99208935, 0.36548855, 0.28590572, 0.44747473, 0.77134446,
        0.7623538 , 0.90432569, 0.6940278 , 0.76471616, 0.54440829,
        0.05399826, 0.53516061, 0.76335065, 0

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [35]:
x = np.random.rand(100)
x

array([0.72883008, 0.74521194, 0.10036673, 0.31253874, 0.95367439,
       0.12454825, 0.67793566, 0.55912682, 0.09332302, 0.02855802,
       0.82854522, 0.18764887, 0.49222239, 0.86047392, 0.40457059,
       0.16770018, 0.33120233, 0.73417973, 0.93775477, 0.79228478,
       0.68930215, 0.70881765, 0.30390448, 0.11483595, 0.04582771,
       0.50731692, 0.02478894, 0.17116644, 0.76758934, 0.10313482,
       0.99581719, 0.12114527, 0.30686683, 0.24161184, 0.24641855,
       0.53192769, 0.05271643, 0.08556   , 0.6793764 , 0.54533342,
       0.82341164, 0.62896877, 0.19094897, 0.64564525, 0.10382331,
       0.19846706, 0.33223868, 0.84336115, 0.35010917, 0.7391985 ,
       0.64268426, 0.31181964, 0.27356753, 0.45399507, 0.32486608,
       0.56543195, 0.48070062, 0.39645341, 0.88177293, 0.49487702,
       0.05032052, 0.53121785, 0.28804913, 0.85860087, 0.70803347,
       0.69478901, 0.74719786, 0.22431034, 0.32411138, 0.67562942,
       0.27466177, 0.79715062, 0.17423425, 0.86332297, 0.49957

In [30]:
x.min(), x.max(), x.argmin(), x.argmax()

(0.13354342022899557, 0.9793084751560305, 9, 1)

### dtype

You can also grab the data type of the object in the array:
arr.dtype

In [36]:
x.shape

(100,)

In [41]:
y = x.reshape(4, 25)

In [43]:
y.shape

(4, 25)

In [34]:
x

array([0.68319284, 0.97930848, 0.93993495, 0.65529592, 0.81566723,
       0.19355814, 0.35299753, 0.15312448, 0.22209017, 0.13354342])

In [33]:
x.dtype

dtype('float64')