# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [3]:
import numpy as np
arr = np.random.randint(35,100, 20)
arr2 = np.random.randint(35,100, 20)

In [2]:
arr

array([51, 94, 78, 85, 78, 70, 85, 84, 55, 80, 38, 55, 80, 93, 97, 50, 89,
       71, 51, 78])

In [4]:
arr2

array([41, 44, 69, 55, 82, 66, 68, 49, 43, 84, 51, 99, 85, 87, 91, 36, 75,
       58, 50, 62])

- Addition and subtraction of two arrays arr + arr and arr - arr
- Multiplication of two arrays arr * arr
- Division of two arrays - Note: Gives a warning on division by zero rather than an error

In [7]:
arr + 20

array([110,  65, 114,  72,  98,  57,  98,  96,  79,  98,  76, 106, 108,
        71,  56,  64,  99, 110, 101, 104])

In [6]:
arr * arr2

array([3690, 1980, 6486, 2860, 6396, 2442, 5304, 3724, 2537, 6552, 2856,
       8514, 7480, 4437, 3276, 1584, 5925, 5220, 4050, 5208])

In [5]:
arr + arr2

array([131,  89, 163, 107, 160, 103, 146, 125, 102, 162, 107, 185, 173,
       138, 127,  80, 154, 148, 131, 146])

In [11]:
arr - arr * .3

array([63. , 31.5, 65.8, 36.4, 54.6, 25.9, 54.6, 53.2, 41.3, 54.6, 39.2,
       60.2, 61.6, 35.7, 25.2, 30.8, 55.3, 63. , 56.7, 58.8])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

- square root using np.sqrt
- exp e^ using np.exp
- max using np.max or can use arr.max() also


In [12]:
arr.min()

36

In [13]:
np.min(arr)

36

In [14]:
np.sqrt(arr)

array([9.48683298, 6.70820393, 9.69535971, 7.21110255, 8.83176087,
       6.08276253, 8.83176087, 8.71779789, 7.68114575, 8.83176087,
       7.48331477, 9.2736185 , 9.38083152, 7.14142843, 6.        ,
       6.63324958, 8.88819442, 9.48683298, 9.        , 9.16515139])

In [16]:
np.std(arr)

18.85974549138986