# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)

In [3]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

- Get a value at an index

In [6]:
arr[12]

IndexError: index 12 is out of bounds for axis 0 with size 11

- Get a value in a range

In [9]:
arr[4:9]

array([4, 5, 6, 7, 8])

In [11]:
arr[:] = 5

In [12]:
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

- Set a value with index range broad cast a value.
- a[0:5] = 300

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [26]:
arr = np.random.randint(0,100,30).reshape(5,6)
arr

array([[22, 70, 41, 91, 42, 48],
       [96, 61,  8, 84,  7, 63],
       [51, 67, 71, 84, 51, 97],
       [24, 41, 42,  3, 73, 40],
       [ 4,  7, 16, 77,  0, 10]])

In [33]:
arr[:, 1:]

array([[70, 41, 91, 42, 48],
       [61,  8, 84,  7, 63],
       [67, 71, 84, 51, 97],
       [41, 42,  3, 73, 40],
       [ 7, 16, 77,  0, 10]])

In [31]:
arr[2:, 3:]

array([[84, 51, 97],
       [ 3, 73, 40],
       [77,  0, 10]])

In [28]:
arr[3][2]

42

In [29]:
arr[3,2]

42

In [20]:
arr

13

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [35]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
sum(arr %2 == 0)

5

In [46]:
sal = np.random.randint(1000,2000,50)

In [47]:
sum(sal > sal.mean())

26

In [36]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [37]:
bool_arr = arr>4

In [38]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [39]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [40]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [13]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])